version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: analytics-postgres
    environment:
      POSTGRES_DB: analytics_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - analytics-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: analytics-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5053:80"
    depends_on:
      - postgres
    networks:
      - analytics-network

  mongo:
    image: mongo:7
    container_name: analytics-mongo
    environment:
      MONGO_INITDB_DATABASE: analytics_db
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - analytics-network

  mongo-express:
    image: mongo-express
    container_name: analytics-mongo-express
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongo:27017/
    ports:
      - "8082:8081"
    depends_on:
      - mongo
    networks:
      - analytics-network

volumes:
  postgres_data:
  mongo_data:

networks:
  analytics-network:
    driver: bridge
