version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: order-service-postgres
    environment:
      POSTGRES_DB: orderdb
      POSTGRES_USER: orderuser
      POSTGRES_PASSWORD: orderpassword
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - order-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: order-service-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@orderservice.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5052:80"
    depends_on:
      - postgres
    networks:
      - order-network

volumes:
  postgres_data:

networks:
  order-network:
    driver: bridge
